sudo: false

cache: bundler

script: "bundle exec rake"

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 1.9.3
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

matrix:
  fast_finish: true
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 1.9.3
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 1.9.3
    gemfile: gemfiles/rails_5.2.gemfile
  - rvm: 2.2.10
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.2.10
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 2.2.10
    gemfile: gemfiles/rails_5.2.gemfile
