language: ruby
sudo: false
cache: bundler
script: "bundle exec rake"
before_install:
  - gem update --system
  - gem install bundler
bundler_args: --without development load_test
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.0
  - ruby-head
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  fast_finish: true
  exclude:
  - rvm: 2.2.10
    gemfile: gemfiles/rails_5.2.gemfile
  - rvm: 2.2.10
    gemfile: gemfiles/rails_edge.gemfile
  - rvm: 2.3.7
    gemfile: gemfiles/rails_edge.gemfile
  - rvm: 2.4.4
    gemfile: gemfiles/rails_edge.gemfile
